import { BankAccount, ChequeBook, Beneficiary, IssuedCheque, ChequePrintSettings, BeneficiaryCategory } from './types';
import { tafqeetKwd } from './utils/tafqeetKwd';

export const INITIAL_CHEQUE_PRINT_SETTINGS: ChequePrintSettings = {
  offsetX: 0,
  offsetY: 0,
  showBackgroundOnPrint: false,
  defaultCrossing: true, // تفعيل خاصية التسطير للشيك (Account Payee Only)
  defaultBearerCrossing: true,
  defaultPrinterName: 'HP LaserJet Pro M404n (درج الشيكات المخصص)',
  chequeDueDateAlertDays: 7,
  templateMode: 'scanned_image', // صورة الشيك الحقيقية الأصلية
  dateOffsetX: 0,
  dateOffsetY: 0,
  dateWidth: 36,
  dateHeight: 8.5,
  dateFontSize: 12,
  payeeOffsetX: 0,
  payeeOffsetY: 0,
  payeeWidth: 120,
  payeeHeight: 8.5,
  payeeFontSize: 13,
  wordsOffsetX: 0,
  wordsOffsetY: 0,
  wordsWidth: 84,
  wordsHeight: 9.5,
  wordsFontSize: 11,
  amountOffsetX: 0,
  amountOffsetY: 0,
  amountWidth: 42,
  amountHeight: 12.5,
  amountFontSize: 14,
};

export const DEFAULT_PRINT_SETTINGS: ChequePrintSettings = INITIAL_CHEQUE_PRINT_SETTINGS;

export const INITIAL_BENEFICIARY_CATEGORIES: BeneficiaryCategory[] = [
  { id: 'vendor', name: 'موردين وشركات تجارية', color: 'blue', description: 'الموردين وتجار الجملة والتوريدات' },
  { id: 'company', name: 'شركات ومؤسسات شقيقة', color: 'purple', description: 'المؤسسات والشركات التابعة أو الشقيقة' },
  { id: 'employee', name: 'موظفين ومستحقات عمالية', color: 'emerald', description: 'رواتب، مكافآت، مستحقات نهاية خدمة' },
  { id: 'government', name: 'جهات ومؤسسات حكومية', color: 'amber', description: 'التأمينات، وزارة المالية، الشؤون والبلدية' },
  { id: 'individual', name: 'أفراد وملاك عقارات', color: 'slate', description: 'إيجارات العقارات، ملاك المنشآت، أفراد' },
];

export const STANDARD_CHEQUE_SIZES = [
  { id: 'size-cbk-std', name: 'شيك تجاري قياسي كويتي (CBK)', widthCm: 18.0, heightCm: 9.0, desc: 'المقاس الكويتي القياسي المعتمد 180×90 مم' },
  { id: 'size-intl-std', name: 'شيك أعمال قياسي دولي', widthCm: 21.0, heightCm: 8.5, desc: 'المقاس الشائع للشركات والمؤسسات 210×85 مم' },
  { id: 'size-corp-wide', name: 'شيك شركات عريض مع كعب', widthCm: 23.5, heightCm: 9.0, desc: 'شيكات الشركات الكبرى والمقاولات 235×90 مم' },
  { id: 'size-mid-pay', name: 'شيك مصرفي متوسط (NBK / KFH)', widthCm: 20.0, heightCm: 8.5, desc: 'مقاس الشيكات الشخصية والتجارية المتوسطة 200×85 مم' },
  { id: 'size-pocket', name: 'شيك جيب للأفراد', widthCm: 17.5, heightCm: 7.5, desc: 'دفاتر الشيكات الصغيرة الخاصة بالأفراد 175×75 مم' },
];

export const INITIAL_BANK_ACCOUNTS: BankAccount[] = [
  {
    id: 'acc-cbk-main',
    accountName: 'حساب العمليات الرئيسي - البنك التجاري',
    bankName: 'البنك التجاري الكويتي (CBK)',
    bankCode: 'CBK',
    accountNumber: '1020491823',
    iban: 'KW18CBKU000000001020491823',
    branchName: 'الفرع الرئيسي - شارع مبارك الكبير (العاصمة)',
    currency: 'د.ك',
    currentBalance: 48500.000,
    isDefault: true,
    status: 'active',
    chequeTemplate: 'CBK',
    chequeWidthCm: 18.0,
    chequeHeightCm: 9.0,
    chequeImageUrl: '/src/assets/images/cbk_cheque_bg_1789993769401.jpg',
    chequeImageName: 'cbk_official_stamp.jpg',
    activeTemplateId: 'tpl-cbk-std',
    chequeTemplates: [
      {
        id: 'tpl-cbk-std',
        name: 'شيك تجاري قياسي CBK (18.0 × 9.0 سم)',
        widthCm: 18.0,
        heightCm: 9.0,
        chequeImageUrl: '/src/assets/images/cbk_cheque_bg_1789993769401.jpg',
        chequeImageName: 'cbk_official_stamp.jpg',
        isDefault: true,
        notes: 'الستامب المعتمد للشيكات التشغيلية اليومية',
      },
      {
        id: 'tpl-cbk-corp',
        name: 'شيك شركات عريض CBK Corporate (23.5 × 9.0 سم)',
        widthCm: 23.5,
        heightCm: 9.0,
        isDefault: false,
        notes: 'دفتر شيكات الشركات الكبرى للمقاولات والمشاريع الكبيرة',
      },
    ],
    createdAt: '2026-01-01',
  },
  {
    id: 'acc-nbk-ops',
    accountName: 'حساب المشاريع والرواتب - بنك الكويت الوطني',
    bankName: 'بنك الكويت الوطني (NBK)',
    bankCode: 'NBK',
    accountNumber: '2039485712',
    iban: 'KW82NBOK000000002039485712',
    branchName: 'فرع شرق - شارع أحمد الجابر',
    currency: 'د.ك',
    currentBalance: 32150.000,
    isDefault: false,
    status: 'active',
    chequeTemplate: 'NBK',
    chequeWidthCm: 20.0,
    chequeHeightCm: 8.5,
    activeTemplateId: 'tpl-nbk-std',
    chequeTemplates: [
      {
        id: 'tpl-nbk-std',
        name: 'شيك الوطني القياسي NBK (20.0 × 8.5 سم)',
        widthCm: 20.0,
        heightCm: 8.5,
        isDefault: true,
        notes: 'المقاس القياسي المعتمد لحسابات المشاريع',
      },
      {
        id: 'tpl-nbk-pay',
        name: 'شيك أوامر الدفع NBK (21.0 × 8.5 سم)',
        widthCm: 21.0,
        heightCm: 8.5,
        isDefault: false,
        notes: 'شيكات الدفع التجاري والتحويلات الخارجية',
      },
    ],
    createdAt: '2026-01-15',
  },
  {
    id: 'acc-kfh-sup',
    accountName: 'حساب التوريدات والاستيراد - بيت التمويل الكويتي',
    bankName: 'بيت التمويل الكويتي (KFH)',
    bankCode: 'KFH',
    accountNumber: '4059681723',
    iban: 'KW35KFH0000000004059681723',
    branchName: 'فرع الفيحاء - ق 4',
    currency: 'د.ك',
    currentBalance: 21700.000,
    isDefault: false,
    status: 'active',
    chequeTemplate: 'KFH',
    chequeWidthCm: 21.0,
    chequeHeightCm: 8.5,
    activeTemplateId: 'tpl-kfh-std',
    chequeTemplates: [
      {
        id: 'tpl-kfh-std',
        name: 'شيك بيتك القياسي KFH (21.0 × 8.5 سم)',
        widthCm: 21.0,
        heightCm: 8.5,
        isDefault: true,
        notes: 'دفتر شيكات بيت التمويل للتوريدات العامة',
      },
      {
        id: 'tpl-kfh-corp',
        name: 'شيك رواتب وشركات KFH (23.0 × 9.0 سم)',
        widthCm: 23.0,
        heightCm: 9.0,
        isDefault: false,
        notes: 'المقاس العريض لمدفوعات الرواتب وكبار الموردين',
      },
    ],
    createdAt: '2026-02-01',
  },
];

export const INITIAL_CHEQUE_BOOKS: ChequeBook[] = [
  // Commercial Bank of Kuwait (CBK) Books
  {
    id: 'cb-cbk-01',
    bankAccountId: 'acc-cbk-main',
    bookCode: 'BK-CBK-2026-01',
    bookName: 'دفتر شيكات التجاري - تشغيلي (50 ورقة)',
    serialFrom: 100001,
    serialTo: 100050,
    totalLeaves: 50,
    currentSerial: 100009,
    receivedDate: '2026-05-10',
    status: 'active',
    notes: 'دفتر الشيكات الرئيسي للعمليات والمدفوعات العامة بالدينار الكويتي',
  },
  {
    id: 'cb-cbk-02',
    bankAccountId: 'acc-cbk-main',
    bookCode: 'BK-CBK-2026-02',
    bookName: 'دفتر شيكات التجاري - احتياطي (50 ورقة)',
    serialFrom: 100051,
    serialTo: 100100,
    totalLeaves: 50,
    currentSerial: 100051,
    receivedDate: '2026-08-20',
    status: 'active',
    notes: 'دفتر جديد جاهز للاستخدام عند نفاد الدفتر الأول',
  },
  // NBK Book
  {
    id: 'cb-nbk-01',
    bankAccountId: 'acc-nbk-ops',
    bookCode: 'BK-NBK-2026-01',
    bookName: 'دفتر شيكات الوطني - مشاريع (50 ورقة)',
    serialFrom: 300001,
    serialTo: 300050,
    totalLeaves: 50,
    currentSerial: 300005,
    receivedDate: '2026-04-15',
    status: 'active',
    notes: 'خاص بمدفوعات وعقود مشاريع التجهيز والمقاولات',
  },
  // KFH Book
  {
    id: 'cb-kfh-01',
    bankAccountId: 'acc-kfh-sup',
    bookCode: 'BK-KFH-2026-01',
    bookName: 'دفتر شيكات بيت التمويل - موردين (50 ورقة)',
    serialFrom: 700001,
    serialTo: 700050,
    totalLeaves: 50,
    currentSerial: 700004,
    receivedDate: '2026-06-01',
    status: 'active',
    notes: 'مخصص لموردي البضائع ومستخلصات التوريد الغذائي',
  },
];

export const INITIAL_BENEFICIARIES: Beneficiary[] = [
  {
    id: 'ben-1',
    nameAr: 'شركة الخليج للتجارة والمقاولات ذ.م.م',
    nameEn: 'Gulf Trading & Contracting Co. W.L.L',
    bankAccountId: 'all',
    category: 'vendor',
    civilIdOrCR: '10492834',
    bankName: 'البنك التجاري الكويتي (CBK)',
    iban: 'KW45CBKU000000001928374650',
    phoneNumber: '+965 22441122',
    notes: 'مورد رئيسي لأعمال الصيانة والتجهيزات الإنشائية',
    status: 'active',
    createdAt: '2026-01-10',
  },
  {
    id: 'ben-2',
    nameAr: 'شركة أوتاد العقارية لإدارة المجمعات',
    nameEn: 'Awtad Real Estate Management',
    bankAccountId: 'acc-cbk-main',
    category: 'company',
    civilIdOrCR: '20491823',
    bankName: 'بنك الكويت الوطني (NBK)',
    iban: 'KW12NBOK000000005849302194',
    phoneNumber: '+965 22998877',
    notes: 'إيجار مقر ومكاتب الفرع الرئيسي وفرع حولي',
    status: 'active',
    createdAt: '2026-01-12',
  },
  {
    id: 'ben-3',
    nameAr: 'المؤسسة العامة للتأمينات الاجتماعية',
    nameEn: 'Public Institution for Social Security (PIFSS)',
    bankAccountId: 'all',
    category: 'government',
    civilIdOrCR: 'PIFSS-KW-GOV',
    bankName: 'بنك الكويت المركزي',
    iban: 'KW00CBKW000000000000000001',
    phoneNumber: '+965 114',
    notes: 'اشتراكات التأمين الاجتماعي الشهرية عن العمالة المسجلة',
    status: 'active',
    createdAt: '2026-01-05',
  },
  {
    id: 'ben-4',
    nameAr: 'المهندس أحمد فؤاد الشامي',
    nameEn: 'Eng. Ahmed Fouad Al-Shami',
    bankAccountId: 'acc-cbk-main',
    category: 'individual',
    civilIdOrCR: '286041209384',
    bankName: 'بيت التمويل الكويتي (KFH)',
    iban: 'KW91KFH000000000849302194',
    phoneNumber: '+965 99887766',
    notes: 'مستشار هندسي واستشارات التراخيص الصناعية',
    status: 'active',
    createdAt: '2026-02-15',
  },
  {
    id: 'ben-5',
    nameAr: 'شركة الغانم للمواد والتجهيزات التجارية',
    nameEn: 'Al-Ghanim Commercial Supplies',
    bankAccountId: 'acc-cbk-main',
    category: 'vendor',
    civilIdOrCR: '39485712',
    bankName: 'البنك التجاري الكويتي (CBK)',
    iban: 'KW55CBKU000000004958673829',
    phoneNumber: '+965 1808080',
    notes: 'توريد أجهزة التكييف والأنظمة الأمنية للفروع',
    status: 'active',
    createdAt: '2026-03-01',
  },
  {
    id: 'ben-6',
    nameAr: 'وزارة التجارة والصناعة (دولة الكويت)',
    nameEn: 'Ministry of Commerce & Industry',
    bankAccountId: 'all',
    category: 'government',
    civilIdOrCR: 'MOCI-KW-GOV',
    bankName: 'بنك الكويت المركزي',
    iban: 'KW00CBKW000000000000000002',
    phoneNumber: '+965 135',
    notes: 'رسوم تجديد التراخيص التجارية والسجل التجاري',
    status: 'active',
    createdAt: '2026-01-01',
  },
  {
    id: 'ben-7',
    nameAr: 'خالد عبد الرحمن المنصور',
    nameEn: 'Khaled Abdulrahman Al-Mansoor',
    bankAccountId: 'all',
    category: 'employee',
    civilIdOrCR: '288120805678',
    bankName: 'بيت التمويل الكويتي (KFH)',
    iban: 'KW35KFH0000000000000987654321',
    phoneNumber: '+965 99112233',
    notes: 'مكافأة إنجاز تسويقية ومستحقات إدارية',
    status: 'active',
    createdAt: '2026-04-10',
  },
];

export const INITIAL_ISSUED_CHEQUES: IssuedCheque[] = [
  // Commercial Bank of Kuwait (CBK) Cheques
  {
    id: 'chk-100001',
    bankAccountId: 'acc-cbk-main',
    chequeBookId: 'cb-cbk-01',
    chequeNumber: 100001,
    chequeNumberStr: '00100001',
    beneficiaryId: 'ben-2',
    beneficiaryName: 'شركة أوتاد العقارية لإدارة المجمعات',
    amount: 1850.000,
    amountInWordsAr: tafqeetKwd(1850.000),
    issueDate: '2026-08-01',
    dueDate: '2026-08-05',
    status: 'cashed',
    cashedDate: '2026-08-06',
    isCrossed: true,
    bearerCrossed: true,
    purpose: 'سداد إيجار مقر الفرع الرئيسي والمكاتب لشهر أغسطس 2026',
    notes: 'تم الخصم والمقاصة من البنك التجاري بنجاح',
    createdBy: 'admin',
    createdAt: '2026-08-01 10:15:00',
  },
  {
    id: 'chk-100002',
    bankAccountId: 'acc-cbk-main',
    chequeBookId: 'cb-cbk-01',
    chequeNumber: 100002,
    chequeNumberStr: '00100002',
    beneficiaryId: 'ben-1',
    beneficiaryName: 'شركة الخليج للتجارة والمقاولات ذ.م.م',
    amount: 3200.750,
    amountInWordsAr: tafqeetKwd(3200.750),
    issueDate: '2026-08-10',
    dueDate: '2026-08-15',
    status: 'cashed',
    cashedDate: '2026-08-17',
    isCrossed: true,
    bearerCrossed: true,
    purpose: 'دفعة مستخلص المرحلة الثانية لأعمال الصيانة والتجهيز',
    notes: 'مرفق فاتورة ضريبية وسند تسليم الأعمال',
    createdBy: 'accountant_kw',
    createdAt: '2026-08-10 11:30:00',
  },
  {
    id: 'chk-100003',
    bankAccountId: 'acc-cbk-main',
    chequeBookId: 'cb-cbk-01',
    chequeNumber: 100003,
    chequeNumberStr: '00100003',
    beneficiaryId: 'ben-3',
    beneficiaryName: 'المؤسسة العامة للتأمينات الاجتماعية',
    amount: 945.500,
    amountInWordsAr: tafqeetKwd(945.500),
    issueDate: '2026-08-25',
    dueDate: '2026-08-28',
    status: 'cashed',
    cashedDate: '2026-08-29',
    isCrossed: true,
    bearerCrossed: true,
    purpose: 'سداد اشتراكات التأمين الاجتماعي عن شهر أغسطس 2026',
    notes: 'إشعار سداد رقم 849302',
    createdBy: 'admin',
    createdAt: '2026-08-25 09:00:00',
  },
  {
    id: 'chk-100004',
    bankAccountId: 'acc-cbk-main',
    chequeBookId: 'cb-cbk-01',
    chequeNumber: 100004,
    chequeNumberStr: '00100004',
    beneficiaryId: 'ben-5',
    beneficiaryName: 'شركة الغانم للمواد والتجهيزات التجارية',
    amount: 1450.000,
    amountInWordsAr: tafqeetKwd(1450.000),
    issueDate: '2026-08-30',
    dueDate: '2026-08-30',
    status: 'cancelled',
    cancelledDate: '2026-08-31',
    cancelReason: 'خطأ في اسم المستفيد تم إلغاء الشيك وإعادة إصداره بالشيك 100005',
    isCrossed: true,
    bearerCrossed: true,
    purpose: 'توريد أجهزة تكييف فرع الفروانية',
    notes: 'تم إتلاف الورقة وتثبيتها بكعب الدفتر',
    createdBy: 'admin',
    createdAt: '2026-08-30 14:20:00',
  },
  {
    id: 'chk-100005',
    bankAccountId: 'acc-cbk-main',
    chequeBookId: 'cb-cbk-01',
    chequeNumber: 100005,
    chequeNumberStr: '00100005',
    beneficiaryId: 'ben-5',
    beneficiaryName: 'شركة الغانم للمواد والتجهيزات التجارية',
    amount: 1450.000,
    amountInWordsAr: tafqeetKwd(1450.000),
    issueDate: '2026-09-01',
    dueDate: '2026-09-10',
    status: 'cashed',
    cashedDate: '2026-09-12',
    isCrossed: true,
    bearerCrossed: true,
    purpose: 'بديل الشيك الملغى 100004 - توريد أجهزة تكييف فرع الفروانية',
    notes: 'تم استلام كشف المقاصة بنجاح',
    createdBy: 'admin',
    createdAt: '2026-09-01 09:30:00',
  },
  {
    id: 'chk-100006',
    bankAccountId: 'acc-cbk-main',
    chequeBookId: 'cb-cbk-01',
    chequeNumber: 100006,
    chequeNumberStr: '00100006',
    beneficiaryId: 'ben-2',
    beneficiaryName: 'شركة أوتاد العقارية لإدارة المجمعات',
    amount: 1850.000,
    amountInWordsAr: tafqeetKwd(1850.000),
    issueDate: '2026-09-02',
    dueDate: '2026-09-25',
    status: 'issued', // لم يصرف بعد / معلق
    isCrossed: true,
    bearerCrossed: true,
    purpose: 'سداد إيجار شهر سبتمبر 2026 لمقرات الفروع',
    notes: 'شيك مؤجل الاستحقاق لتاريخ 25 سبتمبر 2026',
    createdBy: 'accountant_kw',
    createdAt: '2026-09-02 11:00:00',
  },
  {
    id: 'chk-100007',
    bankAccountId: 'acc-cbk-main',
    chequeBookId: 'cb-cbk-01',
    chequeNumber: 100007,
    chequeNumberStr: '00100007',
    beneficiaryId: 'ben-4',
    beneficiaryName: 'المهندس أحمد فؤاد الشامي',
    amount: 750.000,
    amountInWordsAr: tafqeetKwd(750.000),
    issueDate: '2026-09-15',
    dueDate: '2026-09-22',
    status: 'issued', // لم يصرف بعد / معلق
    isCrossed: true,
    bearerCrossed: true,
    purpose: 'أتعاب استشارات هندسية واعتماد مخططات فرع الأحمدي',
    notes: 'سلم للشخص باليد وموقّع بسند استلام',
    createdBy: 'admin',
    createdAt: '2026-09-15 13:00:00',
  },
  {
    id: 'chk-100008',
    bankAccountId: 'acc-cbk-main',
    chequeBookId: 'cb-cbk-01',
    chequeNumber: 100008,
    chequeNumberStr: '00100008',
    beneficiaryId: 'ben-6',
    beneficiaryName: 'وزارة التجارة والصناعة (دولة الكويت)',
    amount: 280.250,
    amountInWordsAr: tafqeetKwd(280.250),
    issueDate: '2026-09-18',
    dueDate: '2026-09-20',
    status: 'issued', // لم يصرف بعد / معلق
    isCrossed: true,
    bearerCrossed: true,
    purpose: 'رسوم تجديد التراخيص الصناعية والتجارية للشركة الأم',
    notes: 'مرفق إشعار المعاملة الوزارية',
    createdBy: 'admin',
    createdAt: '2026-09-18 10:45:00',
  },

  // NBK Cheques
  {
    id: 'chk-300001',
    bankAccountId: 'acc-nbk-ops',
    chequeBookId: 'cb-nbk-01',
    chequeNumber: 300001,
    chequeNumberStr: '00300001',
    beneficiaryId: 'ben-1',
    beneficiaryName: 'شركة الخليج للتجارة والمقاولات ذ.م.م',
    amount: 2500.000,
    amountInWordsAr: tafqeetKwd(2500.000),
    issueDate: '2026-08-05',
    dueDate: '2026-08-08',
    status: 'cashed',
    cashedDate: '2026-08-09',
    isCrossed: true,
    bearerCrossed: true,
    purpose: 'توريد عوازل ومواد تشطيب لمخازن الفروانية',
    notes: 'مصروف من حساب الوطني شرق',
    createdBy: 'admin',
    createdAt: '2026-08-05 10:00:00',
  },
  {
    id: 'chk-300002',
    bankAccountId: 'acc-nbk-ops',
    chequeBookId: 'cb-nbk-01',
    chequeNumber: 300002,
    chequeNumberStr: '00300002',
    beneficiaryId: 'ben-7',
    beneficiaryName: 'خالد عبد الرحمن المنصور',
    amount: 500.000,
    amountInWordsAr: tafqeetKwd(500.000),
    issueDate: '2026-08-20',
    dueDate: '2026-08-20',
    status: 'cashed',
    cashedDate: '2026-08-22',
    isCrossed: true,
    bearerCrossed: true,
    purpose: 'مكافأة استثنائية عن تحقيق الأهداف التشغيلية للربع الثاني',
    notes: 'معتمد بقرار مجلس الإدارة',
    createdBy: 'admin',
    createdAt: '2026-08-20 12:00:00',
  },
  {
    id: 'chk-300003',
    bankAccountId: 'acc-nbk-ops',
    chequeBookId: 'cb-nbk-01',
    chequeNumber: 300003,
    chequeNumberStr: '00300003',
    beneficiaryId: 'ben-1',
    beneficiaryName: 'شركة الخليج للتجارة والمقاولات ذ.م.م',
    amount: 1750.000,
    amountInWordsAr: tafqeetKwd(1750.000),
    issueDate: '2026-09-10',
    dueDate: '2026-09-28',
    status: 'issued', // لم يصرف بعد / معلق
    isCrossed: true,
    bearerCrossed: true,
    purpose: 'الدفعة الختامية لعقد صيانة مخازن العاصمة',
    notes: 'شيك مؤجل الاستحقاق',
    createdBy: 'accountant_kw',
    createdAt: '2026-09-10 14:15:00',
  },
  {
    id: 'chk-300004',
    bankAccountId: 'acc-nbk-ops',
    chequeBookId: 'cb-nbk-01',
    chequeNumber: 300004,
    chequeNumberStr: '00300004',
    beneficiaryId: 'ben-4',
    beneficiaryName: 'المهندس أحمد فؤاد الشامي',
    amount: 600.000,
    amountInWordsAr: tafqeetKwd(600.000),
    issueDate: '2026-09-16',
    dueDate: '2026-09-24',
    status: 'issued', // لم يصرف بعد / معلق
    isCrossed: true,
    bearerCrossed: true,
    purpose: 'إشراف فني على أعمال التمديدات الكهربائية',
    notes: 'تحت المقاصة',
    createdBy: 'admin',
    createdAt: '2026-09-16 11:10:00',
  },

  // KFH Cheques
  {
    id: 'chk-700001',
    bankAccountId: 'acc-kfh-sup',
    chequeBookId: 'cb-kfh-01',
    chequeNumber: 700001,
    chequeNumberStr: '00700001',
    beneficiaryId: 'ben-5',
    beneficiaryName: 'شركة الغانم للمواد والتجهيزات التجارية',
    amount: 2200.000,
    amountInWordsAr: tafqeetKwd(2200.000),
    issueDate: '2026-08-12',
    dueDate: '2026-08-15',
    status: 'cashed',
    cashedDate: '2026-08-16',
    isCrossed: true,
    bearerCrossed: true,
    purpose: 'شراء رافعات يدوية ومعدات تحميل للمستودعات',
    notes: 'منصرف من بيت التمويل الكويتي',
    createdBy: 'admin',
    createdAt: '2026-08-12 09:40:00',
  },
  {
    id: 'chk-700002',
    bankAccountId: 'acc-kfh-sup',
    chequeBookId: 'cb-kfh-01',
    chequeNumber: 700002,
    chequeNumberStr: '00700002',
    beneficiaryId: 'ben-1',
    beneficiaryName: 'شركة الخليج للتجارة والمقاولات ذ.م.م',
    amount: 1100.000,
    amountInWordsAr: tafqeetKwd(1100.000),
    issueDate: '2026-09-05',
    dueDate: '2026-09-18',
    status: 'cashed',
    cashedDate: '2026-09-19',
    isCrossed: true,
    bearerCrossed: true,
    purpose: 'تركيب أرفف معدنية ثقيلة لمخزن الأحمدي',
    notes: 'تم الصرف',
    createdBy: 'admin',
    createdAt: '2026-09-05 13:20:00',
  },
  {
    id: 'chk-700003',
    bankAccountId: 'acc-kfh-sup',
    chequeBookId: 'cb-kfh-01',
    chequeNumber: 700003,
    chequeNumberStr: '00700003',
    beneficiaryId: 'ben-5',
    beneficiaryName: 'شركة الغانم للمواد والتجهيزات التجارية',
    amount: 1650.500,
    amountInWordsAr: tafqeetKwd(1650.500),
    issueDate: '2026-09-14',
    dueDate: '2026-09-30',
    status: 'issued', // لم يصرف بعد / معلق
    isCrossed: true,
    bearerCrossed: true,
    purpose: 'توريد دفعة ثانية من مستلزمات التغليف والكرتون',
    notes: 'شيك مؤجل الاستحقاق لنهاية الشهر',
    createdBy: 'accountant_kw',
    createdAt: '2026-09-14 15:00:00',
  },
];
