import {
  BankReconciliationSettings,
  AccountingTransaction,
  BankStatementTransaction,
  BankReconciliationSession,
  UserReconciliationPermissions
} from './types/reconciliationTypes';

export const DEFAULT_RECONCILIATION_SETTINGS: BankReconciliationSettings = {
  autoExtractDifferences: true, // استخراج تلقائي لكافة الفروقات دون حدود مسبقة
  smallDifferenceLimit: 1.000, // قيمة مرجعية
  bankFeeExpenseAccountId: '5020-01',
  bankFeeExpenseAccountName: 'مصروف عمولات ومصاريف بنكية ورسوم KNET',
  allowedDateToleranceDays: 3,
  allowBatchMatching: true,
  autoDetectDebitCredit: true,
  enableFuzzyMatching: true,
  maskBankAccountsInReports: false,
  customBankName: 'البنك التجاري الكويتي (CBK)',
  customAccountNumber: '0101-998234-01',
};

export const DEFAULT_PERMISSIONS: UserReconciliationPermissions = {
  canView: true,
  canImport: true,
  canEditTransactions: true,
  canCreateJournalEntries: true,
  canApproveFees: true,
  canCloseMonth: true,
  canReopenMonth: true,
  canDeleteSession: true,
  canExportReports: true,
  canManageSettings: true,
};

// Initial Mock Sessions
export const INITIAL_RECONCILIATION_SESSIONS: BankReconciliationSession[] = [
  {
    id: 'rec-session-2026-08',
    bankAccountId: 'acc-cbk-main',
    bankAccountName: 'حساب العمليات الرئيسي - البنك التجاري',
    bankAccountNumber: '1020491823',
    periodStart: '2026-08-01',
    periodEnd: '2026-08-31',
    currency: 'د.ك',
    openingBalanceBank: 42350.000,
    closingBalanceBank: 48500.000,
    openingBalanceAccounting: 42350.000,
    closingBalanceAccounting: 48500.000,
    status: 'closed',
    isMonthClosed: true,
    closedAt: '2026-09-02 11:30:00',
    closedBy: 'المسؤول العام للنظام',
    reconciliationToken: 'REC-CBK-202608-89F4B2',
    notes: 'تم إغلاق شهر أغسطس بتسوية متوازنة بالكامل',
    createdAt: '2026-08-31',
    updatedAt: '2026-09-02',
  },
  {
    id: 'rec-session-2026-09',
    bankAccountId: 'acc-cbk-main',
    bankAccountName: 'حساب العمليات الرئيسي - البنك التجاري',
    bankAccountNumber: '1020491823',
    periodStart: '2026-09-01',
    periodEnd: '2026-09-30',
    currency: 'د.ك',
    openingBalanceBank: 48500.000,
    closingBalanceBank: 53120.450,
    openingBalanceAccounting: 48500.000,
    closingBalanceAccounting: 54180.700,
    status: 'in_progress',
    isMonthClosed: false,
    notes: 'جلسة تسوية شهر سبتمبر 2026 جارية',
    createdAt: '2026-09-20',
    updatedAt: '2026-09-23',
  },
];

// Initial Accounting Transactions pulled from Payroll, Cheques, and Ledger
export const INITIAL_ACCOUNTING_TRANSACTIONS: AccountingTransaction[] = [
  {
    id: 'acc-tx-01',
    journalEntryNumber: 'JV-2026-09-001',
    entryDate: '2026-09-02',
    referenceNumber: 'TRF-PAY-0902',
    description: 'تحويل بنكي - رواتب عمالة فرع السالمية لشهر أغسطس',
    counterAccountName: 'حساب الرواتب المستحقة',
    counterAccountCode: '2110-01',
    debit: 0,
    credit: 3250.000,
    netAmount: -3250.000,
    transferNumber: 'TRF-90214',
    partyName: 'موظفي فرع السالمية',
    createdBy: 'أحمد المحاسب',
    status: 'posted',
    hasAttachment: true,
    sourceModule: 'payroll',
    matchStatus: 'unmatched',
  },
  {
    id: 'acc-tx-02',
    journalEntryNumber: 'JV-2026-09-004',
    entryDate: '2026-09-05',
    referenceNumber: 'CHK-100021',
    description: 'شيك رقم 100021 - سداد فاتورة توريد مواد غذائية',
    counterAccountName: 'شركة المطاحن الأولى للتجارة',
    counterAccountCode: '2010-44',
    debit: 0,
    credit: 1450.750,
    netAmount: -1450.750,
    chequeNumber: '100021',
    partyName: 'شركة المطاحن الأولى للتجارة',
    createdBy: 'فهد الرشيدي',
    status: 'posted',
    hasAttachment: true,
    sourceModule: 'cheques',
    matchStatus: 'unmatched',
  },
  {
    id: 'acc-tx-03',
    journalEntryNumber: 'JV-2026-09-008',
    entryDate: '2026-09-08',
    referenceNumber: 'DEP-8841',
    description: 'إيداع نقدي - مبيعات نهاية الأسبوع فرع الفروانية',
    counterAccountName: 'إيراد مبيعات الفروع',
    counterAccountCode: '4010-02',
    debit: 5200.000,
    credit: 0,
    netAmount: 5200.000,
    partyName: 'فرع الفروانية',
    createdBy: 'سالم الكندري',
    status: 'posted',
    hasAttachment: false,
    sourceModule: 'general_ledger',
    matchStatus: 'unmatched',
  },
  {
    id: 'acc-tx-04',
    journalEntryNumber: 'JV-2026-09-012',
    entryDate: '2026-09-12',
    referenceNumber: 'CHK-100022',
    description: 'شيك رقم 100022 - إيجار مقر الإدارة العامة لشهر سبتمبر',
    counterAccountName: 'مؤسسة الأوقاف والاستثمار العقاري',
    counterAccountCode: '5010-12',
    debit: 0,
    credit: 2800.000,
    netAmount: -2800.000,
    chequeNumber: '100022',
    partyName: 'مؤسسة الأوقاف والاستثمار العقاري',
    createdBy: 'أحمد المحاسب',
    status: 'posted',
    hasAttachment: true,
    sourceModule: 'cheques',
    matchStatus: 'unmatched',
  },
  {
    id: 'acc-tx-05',
    journalEntryNumber: 'JV-2026-09-015',
    entryDate: '2026-09-15',
    referenceNumber: 'KNET-SETTLE-15',
    description: 'تسوية مبيعات شبكة KNET عن الفترة 10-14 سبتمبر',
    counterAccountName: 'وسيط عمليات كي نت K-NET',
    counterAccountCode: '1040-05',
    debit: 4120.500,
    credit: 0,
    netAmount: 4120.500,
    partyName: 'شركة KNET للدفع الإلكتروني',
    createdBy: 'نظام الدفع الآلي',
    status: 'posted',
    hasAttachment: true,
    sourceModule: 'general_ledger',
    matchStatus: 'unmatched',
  },
  {
    id: 'acc-tx-06',
    journalEntryNumber: 'JV-2026-09-018',
    entryDate: '2026-09-18',
    referenceNumber: 'CHK-100023',
    description: 'شيك رقم 100023 - توريد أدوات مكتبية وتقنية',
    counterAccountName: 'مكتبة العجيري والمشاريع',
    counterAccountCode: '5030-08',
    debit: 0,
    credit: 640.250,
    netAmount: -640.250,
    chequeNumber: '100023',
    partyName: 'مكتبة العجيري والمشاريع',
    createdBy: 'فهد الرشيدي',
    status: 'posted',
    hasAttachment: false,
    sourceModule: 'cheques',
    matchStatus: 'unmatched',
  },
  {
    id: 'acc-tx-07',
    journalEntryNumber: 'JV-2026-09-021',
    entryDate: '2026-09-21',
    referenceNumber: 'CHK-100024',
    description: 'شيك رقم 100024 - صيانة أجهزة التكييف والتبريد',
    counterAccountName: 'شركة التبريد الحديثة للتجارة',
    counterAccountCode: '5040-02',
    debit: 0,
    credit: 850.000,
    netAmount: -850.000,
    chequeNumber: '100024',
    partyName: 'شركة التبريد الحديثة للتجارة',
    createdBy: 'أحمد المحاسب',
    status: 'posted',
    hasAttachment: true,
    sourceModule: 'cheques',
    matchStatus: 'unmatched',
  },
  {
    id: 'acc-tx-08',
    journalEntryNumber: 'JV-2026-09-022',
    entryDate: '2026-09-22',
    referenceNumber: 'DEP-8910',
    description: 'إيداع تحويل بنكي - دفعة عقد توريد مستشفى الصباح',
    counterAccountName: 'العملاء - وزارة الصحة',
    counterAccountCode: '1020-03',
    debit: 7850.000,
    credit: 0,
    netAmount: 7850.000,
    partyName: 'وزارة الصحة الكويتية',
    createdBy: 'فهد الرشيدي',
    status: 'posted',
    hasAttachment: true,
    sourceModule: 'general_ledger',
    matchStatus: 'unmatched',
  }
];

// Sample Bank Statement rows mimicking a real Kuwait Commercial Bank (CBK) statement
export const SAMPLE_BANK_STATEMENT_TRANSACTIONS: BankStatementTransaction[] = [
  {
    id: 'bank-tx-01',
    importId: 'imp-01',
    rowNumber: 2,
    transactionDate: '2026-09-02',
    referenceNumber: 'TRF-90214',
    description: 'SALARY TRANSFER WAGES SALMIYA BR',
    debit: 3250.000,
    credit: 0,
    netAmount: -3250.000,
    balanceAfter: 45250.000,
    partyName: 'SALMIYA BRANCH STAFF',
    transferNumber: 'TRF-90214',
    matchStatus: 'unmatched',
  },
  {
    id: 'bank-tx-02',
    importId: 'imp-01',
    rowNumber: 3,
    transactionDate: '2026-09-06',
    referenceNumber: 'CHK-100021',
    description: 'CHEQUE CLEARING NO 100021 FIRST MILLS TRADING',
    debit: 1450.750,
    credit: 0,
    netAmount: -1450.750,
    balanceAfter: 43799.250,
    partyName: 'FIRST MILLS TRADING CO',
    chequeNumber: '100021',
    matchStatus: 'unmatched',
  },
  {
    id: 'bank-tx-03',
    importId: 'imp-01',
    rowNumber: 4,
    transactionDate: '2026-09-08',
    referenceNumber: 'DEP-8841',
    description: 'CASH DEPOSIT BRANCH FARWANIYA SALES',
    debit: 0,
    credit: 5200.000,
    netAmount: 5200.000,
    balanceAfter: 48999.250,
    partyName: 'FARWANIYA BRANCH',
    matchStatus: 'unmatched',
  },
  {
    id: 'bank-tx-04',
    importId: 'imp-01',
    rowNumber: 5,
    transactionDate: '2026-09-13',
    referenceNumber: 'CHK-100022',
    description: 'CHEQUE CLEARING NO 100022 AWQAF REAL ESTATE',
    debit: 2800.000,
    credit: 0,
    netAmount: -2800.000,
    balanceAfter: 46199.250,
    partyName: 'AWQAF REAL ESTATE',
    chequeNumber: '100022',
    matchStatus: 'unmatched',
  },
  {
    id: 'bank-tx-05',
    importId: 'imp-01',
    rowNumber: 6,
    transactionDate: '2026-09-15',
    referenceNumber: 'KNET-SETTLE-15',
    description: 'K-NET MERCHANT SETTLEMENT REF 15',
    debit: 0,
    credit: 4120.000, // Small difference of 0.500 KD (KNET Commission)
    netAmount: 4120.000,
    balanceAfter: 50319.250,
    partyName: 'K-NET PAYMENTS',
    matchStatus: 'unmatched',
  },
  {
    id: 'bank-tx-06',
    importId: 'imp-01',
    rowNumber: 7,
    transactionDate: '2026-09-16',
    referenceNumber: 'CHG-CBK-MONTHLY',
    description: 'CBK ONLINE CORPORATE BANKING MONTHLY SERVICE FEE',
    debit: 5.000,
    credit: 0,
    netAmount: -5.000,
    balanceAfter: 50314.250,
    partyName: 'COMMERCIAL BANK OF KUWAIT',
    matchStatus: 'bank_only',
  },
  {
    id: 'bank-tx-07',
    importId: 'imp-01',
    rowNumber: 8,
    transactionDate: '2026-09-20',
    referenceNumber: 'DIV-CBK-INVEST',
    description: 'DIRECT CREDIT - DIVIDEND EARNINGS KFH FUND',
    debit: 0,
    credit: 215.000,
    netAmount: 215.000,
    balanceAfter: 50529.250,
    partyName: 'KFH INVESTMENT FUND',
    matchStatus: 'bank_only',
  },
  {
    id: 'bank-tx-08',
    importId: 'imp-01',
    rowNumber: 9,
    transactionDate: '2026-09-22',
    referenceNumber: 'TRF-MOH-9910',
    description: 'INCOMING WIRE MOH TREASURY HEALTH MINISTRY',
    debit: 0,
    credit: 7850.000,
    netAmount: 7850.000,
    balanceAfter: 58379.250,
    partyName: 'MINISTRY OF HEALTH',
    matchStatus: 'unmatched',
  },
];
